### PR TITLE
Demo of passing a string as probe fire argument

### PR DESCRIPTION
**Pull request by atifaziz**
This PR demonstrates how to send a string as a probe firing argument using the shortest amount of code and assuming only ASCII characters will be used. The string is encoded using an ANSI code page for simplicity since there's already the [`Marshal.StringToHGlobalAnsi`] method in .NET that does all the heavy-lifting of allocating OS memory, converting and copying the string content and null-terminating it. The ISO 8601 time format will contain ASCII characters only so there's no risk of character corruption. As there's a lot of heavy-lifting going on to marshal the string, it may not be the best option for lightweight tracing in production, but again, this is for demonstration purposes only.

[`Marshal.StringToHGlobalAnsi`]: https://learn.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.marshal.stringtohglobalansi?view=net-8.0

### CODE REVIEW

**Review by gukoff — APPROVED** [review]
Works!

**Comment by gukoff** [comment]
On my machine it also works with the Chinese/Russian characters, accents and various Unicode symbols.

> As there's a lot of heavy-lifting going on to marshal the string, it may not be the best option for lightweight tracing in production, but again, this is for demonstration purposes only.

The only way to avoid heavy-lifting seems to be [this](https://learn.microsoft.com/en-us/dotnet/standard/native-interop/best-practices#string-parameters), but using `StringMarshalling.Utf16` breaks `bpftrace` tracing for me...

**Comment by atifaziz** [comment]
> On my machine it also works with the Chinese/Russian characters, accents and various Unicode symbols.

Interesting and thanks for testing. What was your machine and testing environment? I'm honestly baffled as to how ANSI code page translations could work so seamlessly, thus my question.

> The only way to avoid heavy-lifting seems to be [this](https://learn.microsoft.com/en-us/dotnet/standard/native-interop/best-practices#string-parameters), but using `StringMarshalling.Utf16` breaks `bpftrace` tracing for me...

Thanks for the pointer. That makes sense, but I was thinking that another way to avoid that would be to let the caller manage some sort of temporary working pool from the heap that's pre-allocated.

**Comment by atifaziz** [comment]
> > On my machine it also works with the Chinese/Russian characters, accents and various Unicode symbols.
> 
> Interesting and thanks for testing. What was your machine and testing environment? I'm honestly baffled as to how ANSI code page translations could work so seamlessly, thus my question.

I dug deeper into the sources and it looks like that [`Marshal.StringToHGlobalAnsi` internally calls `StringToAnsiString`](https://github.com/dotnet/runtime/blob/v8.0.8/src/libraries/System.Private.CoreLib/src/System/Runtime/InteropServices/Marshal.cs#L929), which [for *nix platforms](https://github.com/dotnet/runtime/blob/v8.0.8/src/libraries/System.Private.CoreLib/src/System/Runtime/InteropServices/Marshal.Unix.cs#L39), is implemented to use UTF-8 and not ANSI code pages. This seems to clear up the smoke and explain why it works with Chinese/Russian characters, accents and various Unicode symbols. The interoperability methods are named to be very Windows-centric for historical reason, but since this is [by-design](https://github.com/dotnet/runtime/issues/26816#issuecomment-405021337), the documentation could use a comment in the remarks section of the methods for those concerned with portability (to avoid confusion and being paranoid as I was). There is [a method on `Marshal` called `StringToHGlobalUTF8`](https://github.com/dotnet/runtime/blob/08338fcaa5c9b9a8190abb99222fed12aaba956c/src/libraries/System.Private.CoreLib/src/System/Runtime/InteropServices/Marshal.cs#L956), which would be clearer to use in code, but unfortunately it's private. There is however [`Marshal.StringToCoTaskMemUTF8`](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.marshal.stringtocotaskmemutf8?view=net-8.0) and apparently it [uses the same allocator (albeit the name) as `Marshal.StringToHGlobalAnsi`](https://github.com/dotnet/runtime/blob/57a4b04303ebb5a9418814d5d2778b08150a507b/src/libraries/System.Private.CoreLib/src/System/Runtime/InteropServices/Marshal.Unix.cs#L74) on *nix platforms, but as far as clarity of names goes, you lose either on the string encoding or the allocator being confusing.

**Pull request merged**
